### ISSUE TITLE
Feature request: replace constants

### ISSUE THREAD

**Issue by andria-dev** [fwilkerson/microenvi#2]
## Environment variables need to be replaced with their values
Specifically, just using React seems to require `prop-types/checkPropTypes.js` which runs
```
if (process.env.NODE_ENV === 'production') {
```
But it would make sense to make this feature extend to more than just `process.env.XYZ`.
This is currently preventing me from using microenvi at all.

EDIT:
I found out that **microbundle does, in fact, support defining (replacing) constants**.
So I'm going to make a pull request that just adds that cli option and passes it directly to microbundle, as well as, adds the option to the README.

**Comment by ChrisBrownie55** [comment]
Another concern might be different constants values for different modes in which case a file that exports the constants might be the best idea because it will be run in node.js which will allow you to see `process.env.XYZ`.

I got the idea from https://github.com/developit/microbundle/issues/181#issuecomment-423480135:
```node
/* Possible filenames:
 * constants.config.js
 * definitions.config.js
 */

export default { // or module.exports = {
  HOST: process.env.NODE_ENV === 'production' ? 'https://example.com/' : 'localhost',
  PORT: 4200,
  'process.env.NODE_ENV': process.env.NODE_ENV
};
```

And I know that microenvi, like _microbundle_, is supposed to have zero configuration but this is, quite literally, a necessity to use something like React and still doesn't technically necessitate any configuration to use microenvi.

I'll probably make a pull request soon with a possible solution 👍
